config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  #devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_scope :user do
    get 'logout', to: 'devise/sessions#destroy'
  end
  devise_for :users, controllers: { registrations: 'registrations' }

    ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :orders, only: [:index]

  root "products#index"

  post 'add_to_cart', to: 'carts#add_to_cart'
  post 'place_order', to: 'carts#place_order'

  patch 'update_cart', to: 'carts#update_cart'
  delete 'remove_from_cart', to: 'carts#remove_from_cart'
  patch 'update_address', to: 'users#update_address'

  resources :carts do
    get 'checkout', on: :collection 
  end

  namespace :admin do
    resources :customer_orders, only: [:index]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_one_attached :image

  include Kaminari::PageScopeMethods

  validates :name, presence: true

  validates :description, presence: true

  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  validates :category_id, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "description", "id", "id_value", "name", "price", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["category"]
  end

  def self.search(query)
    if query.present?
      where("name LIKE ? OR description LIKE ?", "%#{query}%", "%#{query}%")
    else
      all
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all

    if params[:query].present? || params[:category_id].present?
      @products = @products.search(params[:query]) if params[:query].present?
      if params[:category_id].present?
        @products = @products.where(category_id: params[:category_id])
      end
    end

    case params[:filter]
    when "on_sale"
      @products = @products.where.not(discount_price: nil)
    when "new"
      @products = @products.where("created_at >= ?", 3.days.ago)
    when "recently_updated"
      @products = @products.where("created_at < updated_at AND updated_at >= ?", 3.days.ago)
    end

    @products = @products.page(params[:page]).per(20)
  end

  def show
    @product = Product.find(params[:id])
    @category = Category.find(@product.category_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3"> 
      <%= form_tag products_path, method: :get do %>
        <div class="input-group mb-3">
          <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search by name or description", onchange: "submitForm()" %>
          <%= select_tag :category_id, options_from_collection_for_select(Category.all, :id, :name, params[:category_id]), include_blank: "All Categories", class: "form-control" %>
          <div class="input-group-append">
            <%= submit_tag "Search", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <%= form_tag products_path, method: :get do %>
    <div class="form-group">
      <%= select_tag :filter, options_for_select({ 'All Products' => nil, 'On Sale' => 'on_sale', 'New Products' => 'new', 'Recently Updated' => 'recently_updated' }, params[:filter]), class: 'form-control' %>
    </div>
    <%= submit_tag 'Filter', class: 'btn btn-primary' %>
  <% end %>
</div>

<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Category</th>
        <th>Buy it</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= link_to product.name, product_path(product) %></td>
          <td><%= link_to product.description, product_path(product) %></td>
          <td><%= link_to product.discount_price.present? ? product.discount_price : product.price,product_path(product) %></td>
          <td><%= link_to product.category.name, product_path(product) %></td>
          <td><%= button_to 'Add to Cart', add_to_cart_path(product_id: product.id), method: :post, class: 'btn btn-primary' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="container">
  <%= paginate @products %>
</div>

app/views/products/show.html.erb
<div class="container">
  <h1><%= @product.name %> Details</h1>
  <div class="row">
    <div class="col-md-6">
      <p><strong>Description:</strong> <%= @product.description %></p>
      <% if @product.discount_price.present? %>
        <p><strong>Price:</strong> <%= number_to_currency(@product.price) %></p>
        <p><strong>Discount Price:</strong> <%= number_to_currency(@product.discount_price) %></p>
      <% else %>
        <p><strong>Price:</strong> <%= number_to_currency(@product.price) %></p>
      <% end %>
      <p><strong>Category Products:</strong> <%= link_to @product.category.name, category_path(@product.category) %></p>
    </div>
  </div>
</div>